### ISSUE TITLE
scale_fcst doesn't work with lagging

### ISSUE THREAD

**Issue by uandrae** [andrew-MET/harpPoint#12]
Using

```
verif_val <- ens_read_and_verify(
  start_date     = 201912020000,
  end_date       = 201912021800,
  parameter      = "T2m",
  by             = "6h",
  fcst_model     = c('CMEPS_preop'),
  lags           =  list(CMEPS_preop = c("0h","1h","2h","3h","4h","5h")),
  fcst_path      = "/nobackup/opdata/verif/HARPresults/FCtables/",
  fctable_file_template = "{eps_model}/{YYYY}/{MM}/FCTABLE_{parameter}_{YYYY}{MM}_{HH}.sqlite",
  obs_path       = "/nobackup/opdata/verif/HARPresults/OBS",
  lead_time      = seq(0,6,3),
  thresholds     = c(-20,-10,-5,0,5,10,15,20,25),
  num_iterations = 1,
  scale_fcst = fcst_scales,
  scale_obs  = obs_scales,
  verif_path = "."
)

```

and

 ```
 fcst_scales <- list( CMEPS_preop = list(scale_factor = -273.15, new_units = "C", multiplicative = FALSE))
  obs_scales <- list(scale_factor = -273.15, new_units = "C", multiplicative = FALSE)

```
Produces erroneous scores with spread skill on the order of ~100. However if we skip the lagging by

`  lags           =  list(CMEPS_preop = c("0h")),`

the substraction of 273.15 seems to work properly and we are back to normal scores. Something is going wrong with the lagged part.

**Comment by andrew-MET** [comment]
Is it the spread, the RMSE, or both that have large values?

**Comment by uandrae** [comment]
Both. 


![spread_skill_T2m_CMEPS_preop+MEPS_prod_shifted_6h+MEPS_prod_201911120000-201912041800](https://user-images.githubusercontent.com/19548229/70994315-3c957100-20ce-11ea-8c9e-f183425089fb.png)

**Comment by andrew-MET** [comment]
OK. I probably don't have time to investigate before then end of the year, but will try and sort it out in January.

**Comment by mpartio** [comment]
Any progress here? We are going live with CMEPS change in a couple of weeks so it would be nice to be able to verify that correctly from the get-go.

**Comment by andrew-MET** [comment]
Not going to be able to look at it until next week I'm afraid. Other commitments.

**Comment by andrew-MET** [comment]
Lagged columns weren't being scaled. Fixed now: https://github.com/andrew-MET/harpPoint/commit/cc9c24b384068bc77dbffedbd174621d85d0256f
