### ISSUE TITLE
ecs_read_and_verify(): keep_unshifted does not work with multiple file_templates

### ISSUE THREAD

**Issue by mpartio** [andrew-MET/harpPoint#15]
I am verifying for lagged MEPS_prod and IFSENS, and specifying a separate file_template for both producers and setting keep_unshifted=TRUE does not work:

```
$ unzip keep_unshifted.zip 
Archive:  keep_unshifted.zip
  inflating: OBSTABLE_2020.sqlite    
  inflating: test.R                  
$ Rscript test.R 
[1] "Thresholds:  990 1000"
[1] "Lead times:  0 3 6 9 12"
Getting Pmsl observations for 202002040000-202002060600

Reading: ./OBSTABLE_2020.sqlite
Lead time: 0 ( Iteration 1 of 5 )
================================================================================
Error: You must have either 1 'file_template', or there must be the same number of elements
in 'file_template' as in 'fcst_model'.
Execution halted
```

[keep_unshifted.zip](https://github.com/andrew-MET/harpPoint/files/4203091/keep_unshifted.zip)

**Comment by andrew-MET** [comment]
Fixed: https://github.com/andrew-MET/harpPoint/commit/583d633d96a7f5e4e1a59d1e1059c11d2f6e5dd6

Also a couple of things:
- You might want to use the built in file templates "fctable_eps" and "fctable_eps_all_leads". Run show_file_templates() from harpIO to show the templates
- For fcst_shifts you don't need to specify the 0 shifts 
- You appear to be doing lagging and shifting. This won't actually work as the shift will overwrite the lags with just 1 value. Is this something you really want to do? It seems very much like an edge case and I'm unlikely to prioritise it any time in the near future.

**Comment by mpartio** [comment]
> You appear to be doing lagging and shifting. This won't actually work as the shift will overwrite the lags with just 1 value. Is this something you really want to do? 

Probably not, I'm far from domain expert here. Ulf suggested not to use shifting so I removed it.
