### ISSUE TITLE
Feature request: add scaling for ens_read_and_verify()

### ISSUE THREAD

**Issue by mpartio** [andrew-MET/harpPoint#3]
Verifying Pmsl between MEPS_prod and IFSENS cannot be done because one has unit hPa and other Pa. Can we have some method of passing scaling information when calling ens_read_and_verify()?

**Comment by andrew-MET** [comment]
This should be possible. I imagine the semantics of the argument would be something like:

```
scale_forecast = list(
  IFSENS = list(
    scale_factor = 0.01, new_units = "hPa", multiplicative = TRUE
  )
)
```
and then `scale_point_forecast()` would be called internally.

Also I guess there should be a similar `scale_obs` argument as well.

**Comment by andrew-MET** [comment]
done here: https://github.com/andrew-MET/harpPoint/commit/59052c2f0854ac9537eff2141b1bfaba1d4b2da8

The syntax is as the comment above, except that the argument is `scale_fcst`

For `scale_obs` the syntax is the same except there is no outer list as you don't have to specify a forecast model.

**Comment by mpartio** [comment]
Works like a charm! This also solved my other problem that I didn't report yet, which was that I wanted to verify T2m in Celsius and not Kelvins!
