### ISSUE TITLE
Feature request: add lagging for ens_read_and_verify()

### ISSUE THREAD

**Issue by mpartio** [andrew-MET/harpPoint#4]
Similar to https://github.com/andrew-MET/harpIO/issues/5: can we have a method to pass lagging information with ens_read_and_verify()?

**Comment by andrew-MET** [comment]
fixed: https://github.com/andrew-MET/harpPoint/commit/d7fe4a8d2cfad63dcafa735aec2f291564960643

The argument `lags` is used in the same way as in `read_point_forecast` i.e. to specify the lags of the raw model data, and is a named list.
`lag_fcst_models` is used to specify the models to lag once read in. Is equivalent to the `fcst_models` argument for `lag_forecast()` 
`parent_cycles` is the same as for `lag_forecast()`
`fcst_shifts` is a named list used to specify how many hours you want to shift model start times and lead times by in time to simulate lagging.
`keep_unshifted` is a logical to specify whether you also want to keep the unshifted data. Note the default is FALSE.

Shifting is done by the new function, `shift_forecast()`

An example would be: 
```
ens_read_and_verify(
  ...,
  lags = list(
    CMEPS_expA = c("0h", "1h", "2h", "3h", "4h", "5h"),
    CMEPS_expB = c("0h", "1h", "2h", "3h", "4h", "5h"),
    MEPS_prod  = "0h"
  ),
  lag_fcst_models = c("CMEPS_expA", "CMEPS_expB"),
  parent_cycles   = seq(0, 18, 6),
  fcst_shifts     = list(MEPS_prod = 6),
  ...
)  
```
