### ISSUE TITLE
reading 6h precip when asking for 3h

### ISSUE THREAD

**Issue by andrew-MET** [andrew-MET/harpPoint#8]
In the log for AccPcp3h it looks very much like it reads 6h precipitation?

```
Running verify.R for c('CMEPS_preop','MEPS_prod'), AccPcp3h 

Getting AccPcp3h observations for 201908150000-201910160000

Reading: /nobackup/opdata/verif/HARPresults/OBS/OBSTABLE_2019.sqlite
Deriving 6h precipitation from 12h precipitation
Getting AccPcp6h observations.

```

_Originally posted by @uandrae in https://github.com/andrew-MET/harpPoint/issues/7#issuecomment-543234640_

**Comment by andrew-MET** [comment]
It does read 6h preciptation. And 12 h precipitation. and what 3h precipitation is there. Which is almost nothing. It then uses the offsets in time between the 6 h and 12h precip to calculate the 3 hour precip. Giving you a lot more observations than the tiny handful you'd otherwise have.

**Comment by uandrae** [comment]
OK, sounds like a nice feature. I have some thoughts about the observation frequency but that's not a HARP issue.
