### ISSUE TITLE
fcdate not found

### ISSUE THREAD

**Issue by andrew-MET** [andrew-MET/harpPoint#9]
Reading: /nobackup/opdata/verif/HARPresults/FCtables//MEPS_prod/2019/10/FCTABLE_Pcp_201910_12.sqlite
Reading: /nobackup/opdata/verif/HARPresults/FCtables//MEPS_prod/2019/10/FCTABLE_Pcp_201910_18.sqlite
Error: Column `fcdate` not found in `.data`
Backtrace:
     █
  1. ├─harpPoint::ens_read_and_verify(...)
  2. │ ├─`%>%`(...)
  3. │ │ └─base::eval(lhs, parent, parent)
  4. │ │   └─base::eval(lhs, parent, parent)
  5. │ └─harpIO::read_point_forecast(...)
  6. │   ├─`%>%`(...)
  7. │   │ └─base::eval(lhs, parent, parent)
  8. │   │   └─base::eval(lhs, parent, parent)
  9. │   └─purrr::pmap(...)
 10. │     └─harpIO:::.f(...)
 11. │       └─harpIO:::read_fctable(...)
 12. │         └─`%>%`(...)
 13. │           ├─base::withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
 14. │           └─base::eval(quote(`_fseq`(`_lhs`)), env, env)
 15. │             └─base::eval(quote(`_fseq`(`_lhs`)), env, env)
 16. │               └─harpIO:::`_fseq`(`_lhs`)
 17. │                 └─magrittr::freduce(value, `_function_list`)
 18. │                   ├─base::withVisible(function_list[[k]]
Execution halted
Not running past 30 days verification
Not running monthly verification
Not running seasonal verification
Finished

_Originally posted by @uandrae in https://github.com/andrew-MET/harpPoint/issues/7#issuecomment-543181953_

**Comment by andrew-MET** [comment]
Is this because it's lead time 0?

**Comment by uandrae** [comment]
You're probably right, it works better when I exclude +0h.

**Comment by andrew-MET** [comment]
I'll look into making it fail more elegantly and carry on with the next lead time.

**Comment by andrew-MET** [comment]
Do you have the whole function call that caused this to happen? Because I get the error message I was expecting when lead time is zero: "Error: At least one of lead_time must be greater than or equal to the accumulation time: 3h", so it must be something else...

**Comment by andrew-MET** [comment]
ens_read_and_verify now skips to the next iteration if the lead time is shorter than the accumulation time https://github.com/andrew-MET/harpPoint/commit/ce632edac09b15a9ae9bc149b777033d6516c4ed. I was able to recreate the first problem when fcst_shifts were specified with accumulated precip and fixed it in https://github.com/andrew-MET/harpIO/commit/a603d1887546d41a930a88d776ddc6293cd0bb4b
